# LEARN_FUNCTIONS_PART2

## <font color="cyan">Understand the Dataset Using info()</font>
```
df.info()
The info() method displays:
Column names
Number of non-null values
Data type of every column
Total memory usage
```

In [1]:
import pandas as pd
store_details=pd.read_csv("samplesuperstore.csv")
store_details

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [2]:
store_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

## <font color="cyan">to view numwerical and categorical col</font>
use .selectdatatype

In [7]:

numerical_col=store_details.select_dtypes(include=["int64","float64"]).columns
for col in numerical_col:
    print(col)

Row ID
Sales
Quantity
Discount
Profit

In [8]:
numerical_col

Index(['Row ID', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')

In [9]:
categorical_col=store_details.select_dtypes(include=["object"]).columns
categorical_col

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name'],
      dtype='object')

In [11]:
for col in categorical_col:
    print(col)

Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country/Region
City
State/Province
Postal Code
Region
Product ID
Category
Sub-Category
Product Name

## <font color="cyan">Statistical Summary of Numerical Columns</font>
```
df.describe()

The describe() method provides:
Statistic	Meaning
count	Number of available values
mean	Average
std	Standard deviation
min	Minimum value
25%	First quartile
50%	Median
75%	Third quartile
max	Maximum value

```

In [12]:
store_details.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

## <font color="cyan">.describe() at selected col</font>

In [20]:
store_details[["Product ID" ,"Customer ID"]].describe()

             Product ID Customer ID
count             10194       10194
unique             1862         804
top     FUR-FU-10004270    WB-21850
freq                 20          41

## <font color="cyan">.describe() at datatypes</font>

In [21]:
store_details.select_dtypes(include="int64").describe()

             Row ID      Quantity
count  10194.000000  10194.000000
mean    5097.500000      3.791838
std     2942.898656      2.228317
min        1.000000      1.000000
25%     2549.250000      2.000000
50%     5097.500000      3.000000
75%     7645.750000      5.000000
max    10194.000000     14.000000

In [23]:
store_details.describe(include="int64")

             Row ID      Quantity
count  10194.000000  10194.000000
mean    5097.500000      3.791838
std     2942.898656      2.228317
min        1.000000      1.000000
25%     2549.250000      2.000000
50%     5097.500000      3.000000
75%     7645.750000      5.000000
max    10194.000000     14.000000

## Check Missing Values
```
Missing values represent unavailable or empty information.

df.isnull()

This produces a DataFrame containing True and False.
True means the value is missing.
False means the value is available.
_________________________________________________________
To count missing values in each column:
df.isnull().sum()
________________________________________________________
To display only columns containing missing values:
missing_values = df.isnull().sum()
print(missingvalues[missingvalues > 0])
________________________________________________________
To calculate the missing-value percentage:
missing_percentage = df.isnull().sum() / len(df) * 100
print(missing_percentage)
The uploaded dataset currently contains no missing values, but checking for them is still an essential EDA step.
```

In [24]:
store_details.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [25]:
store_details.isnull().count()

Row ID            10194
Order ID          10194
Order Date        10194
Ship Date         10194
Ship Mode         10194
Customer ID       10194
Customer Name     10194
Segment           10194
Country/Region    10194
City              10194
State/Province    10194
Postal Code       10194
Region            10194
Product ID        10194
Category          10194
Sub-Category      10194
Product Name      10194
Sales             10194
Quantity          10194
Discount          10194
Profit            10194
dtype: int64

In [30]:
store_details.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [2]:
import pandas as pd
stu_details=pd.read_csv("students_.csv")
stu_details

,Student_ID,Name,Gender,Department,Email,Phone,Attendance,Fee,Join_Date,City,Score
0,ST1497,Rahul,female,AI&DS,NaN,9876543210,NaN,45k,2026-01-31,Bangalore,NaN
1,ST1350,Aisha,NaN,AI&DS,NaN,+91-9876543210,85%,"?45,000",10/02/2025,NaN,69
2,ST1144,John,m,I.T,NaN,09876543210,0.78,"?60,500",09/09/2025,Chennai,105
3,ST1336,Sara,Male,Computer Science,saragmail.com,98765 43210,92,45000,29 Jan 26,Chennai,100
4,ST1509,Rahul,female,Computer Science,NaN,9876543210,92,45k,23 Apr 26,Delhi,NaN
...,...,...,...,...,...,...,...,...,...,...,...
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
stu_details.isna()

,Student_ID,Name,Gender,Department,Email,Phone,Attendance,Fee,Join_Date,City,Score
0,False,False,False,False,True,False,True,False,False,False,True
1,False,False,True,False,True,False,False,False,False,True,False
2,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
994,True,True,True,True,True,True,True,True,True,True,True
995,True,True,True,True,True,True,True,True,True,True,True
996,True,True,True,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,True

In [36]:
stu_details.isna().count()

Student_ID    999
Name          999
Gender        999
Department    999
Email         999
Phone         999
Attendance    999
Fee           999
Join_Date     999
City          999
Score         999
dtype: int64

In [38]:
stu_details.isna().sum()

Student_ID    399
Name          429
Gender        475
Department    399
Email         565
Phone         506
Attendance    495
Fee           487
Join_Date     399
City          492
Score         513
dtype: int64

In [3]:
missing_percentage=(stu_details.isna().sum()/len(stu_details))*100
missing_percentage

Student_ID    39.939940
Name          42.942943
Gender        47.547548
Department    39.939940
Email         56.556557
Phone         50.650651
Attendance    49.549550
Fee           48.748749
Join_Date     39.939940
City          49.249249
Score         51.351351
dtype: float64

## <font color="cyan">Handling the Missing Values</font>
```
Method:01
-using dropna()
-use it carefully because it remove the missing value permanently
eg; df["Sales"]=df["sales"].dropna(inplace=True)

Method:02
-using fillna().mean()
-use fillna() to fillnumerical value at missing place
eg; df["sales"]=df["sales"].fillna(df["sales"].mean())

Method 3: 
-Fill numerical missing values using the median
eg;df["Profit"] = df["Profit"].fillna(df["Profit"].median())

Method 4:
-Fill categorical missing values using the mode
eg;df["Region"] = df["Region"].fillna(df["Region"].mode()[0])
[0] because it return first indexed repeatative value that means mode Value

Method 5: 
-Fill missing values with a custom value
eg;df["Region"] = df["Region"].fillna("Unknown")

Choosing a method
Use the mean when values are normally distributed.
Use the median when outliers are present.
Use the mode for categorical values.
Remove rows only when missing records are very few and unimportant.
```

In [4]:
stu_details.dtypes

Student_ID    object
Name          object
Gender        object
Department    object
Email         object
Phone         object
Attendance    object
Fee           object
Join_Date     object
City          object
Score         object
dtype: object

In [16]:
for col in stu_details.columns:
    stu_details[col]=stu_details[col].fillna(stu_details[col].mode()[0])
stu_details.head(50)

,Student_ID,Name,Gender,Department,Email,Phone,Attendance,Fee,Join_Date,City,Score
0,ST1497,Rahul,female,AI&DS,balakrishnan@gamil.com,9876543210,92,45k,2026-01-31,Bangalore,AB
1,ST1350,Aisha,M,AI&DS,balakrishnan@gamil.com,+91-9876543210,85%,"?45,000",10/02/2025,Delhi,69
2,ST1144,John,m,I.T,balakrishnan@gamil.com,09876543210,0.78,"?60,500",09/09/2025,Chennai,105
3,ST1336,Sara,Male,Computer Science,saragmail.com,98765 43210,92,45000,29 Jan 26,Chennai,100
4,ST1509,Rahul,female,Computer Science,balakrishnan@gamil.com,9876543210,92,45k,23 Apr 26,Delhi,AB
5,ST1333,Priya,female,IT,priya@gamil.com,09876543210,92,45k,17 May 25,Delhi,105
6,ST1279,Monica,M,AI DS,monica@gmail.com,9876543210,0.78,"?45,000",23 Jun 25,Delhi,83
7,ST1146,Huzaifa,Female,AI&DS,huzaifa@gmail.com,9876543210,Absent,"?45,000",14 Dec 25,Pune,105
8,ST1340,Balakrishnan,Female,AI&DS,balakrishnan@gamil.com,98765 43210,0.78,45000,2025-12-30,Hyderabad,-5
9,ST1108,Balakrishnan,m,IT,balakrishnan@gamil.com,9876543210,0.78,45k,29/04/2026,Delhi,105
10,ST1415,Deepak,F,AI&DS,deepak@gamil.com,9876543210,101%,"?60,500",14 Apr 26,Delhi,24
11,ST1224,mOhammed,F,I.T,mohammedgmail.com,9876543210,0.78,"?60,500",30/04/2026,Pune,35
12,ST1072,Sara,Female,CSE,sara@gamil.com,98765 43210,92,"?45,000",2025-12-23,Bangalore,105
13,ST1267,Huzaifa,m,AI DS,balakrishnan@gamil.com,98765 43210,92,Paid,2026-05-06,Chennai,AB
14,ST1338,John,Female,Artificial Intelligence,john@gamil.com,9876543210,92,Paid,05 Apr 26,Chennai,AB
15,ST1240,mOhammed,Male,CSE,mohammed@gamil.com,9876543210,92,45k,19/05/2025,Delhi,84
16,ST1196,Sara,M,AI DS,balakrishnan@gamil.com,9876543210,Absent,45000,10 Mar 25,Chennai,105
17,ST1453,Sara,M,IT,balakrishnan@gamil.com,+91-9876543210,101%,Paid,03 Feb 25,Hyderabad,-5
18,ST1331,Rahul,Male,AI DS,rahulgmail.com,09876543210,92,"?60,500",22/04/2025,Delhi,AB
19,ST1355,Deepak,female,AI&DS,balakrishnan@gamil.com,+91-9876543210,85%,"?45,000",13/10/2025,Delhi,70
20,ST1179,Rahul,Male,Artificial Intelligence,balakrishnan@gamil.com,+91-9876543210,0.78,45k,03 Feb 25,Hyderabad,AB
21,ST1337,Balakrishnan,female,Computer Science,balakrishnan@gmail.com,9876543210,92,45000,2025-10-25,Chennai,AB
22,ST1329,Monica,m,AI DS,balakrishnan@gamil.com,+91-9876543210,0.78,45k,2026-02-01,Bangalore,-5
23,ST1203,mOhammed,male,AI DS,mohammed@gmail.com,9876543210,85%,Paid,04/02/2026,Chennai,105
24,ST1255,Aisha,female,Artificial Intelligence,balakrishnan@gamil.com,+91-9876543210,101%,"?60,500",17 Jul 25,Bangalore,AB
25,ST1303,Huzaifa,M,AIDS,huzaifa@gamil.com,+91-9876543210,0.78,45000,2025-09-13,Bangalore,AB
26,ST1175,Balakrishnan,female,I.T,balakrishnan@gmail.com,9876543210,92,45000,26 Feb 25,Bangalore,-5
27,ST1388,Balakrishnan,Male,I.T,balakrishnan@gamil.com,09876543210,0.78,45k,26/10/2025,Bangalore,63
28,ST1138,Balakrishnan,m,IT,balakrishnangmail.com,+91-9876543210,85%,Paid,2025-12-16,Pune,105
29,ST1487,Monica,female,AI DS,monica@gmail.com,+91-9876543210,Absent,45k,28/02/2025,Hyderabad,AB
30,ST1338,Sara,male,AI DS,sara@gamil.com,+91-9876543210,92,"?60,500",10 Feb 25,Hyderabad,-5
31,ST1176,Rahul,M,AIDS,rahul@gmail.com,09876543210,85%,"?45,000",30/05/2025,Delhi,AB
32,ST1248,Balakrishnan,Male,AIDS,balakrishnan@gamil.com,98765 43210,92,Paid,04 May 25,Chennai,AB
33,ST1441,Deepak,m,AI&DS,user@gamil.com,+91-9876543210,Absent,Paid,29/01/2026,Delhi,-5
34,ST1187,Balakrishnan,M,AIDS,balakrishnan@gmail.com,+91-9876543210,101%,45000,12 Sep 25,Bangalore,AB
35,ST1316,Balakrishnan,Male,IT,balakrishnan@gamil.com,98765 43210,0.78,45000,21 Oct 25,Delhi,AB
36,ST1420,Aisha,M,IT,aisha@gamil.com,9876543210,85%,"?60,500",28 Sep 25,Delhi,105
37,ST1404,Rahul,F,AI&DS,balakrishnan@gamil.com,+91-9876543210,92,Paid,07 Jan 26,Delhi,65
38,ST1112,Rahul,female,Computer Science,balakrishnan@gamil.com,9876543210,92,"?60,500",2025-03-11,Hyderabad,105
39,ST1440,Rahul,m,I.T,rahul@gamil.com,98765 43210,101%,45000,06/12/2025,Delhi,-5
40,ST1449,Huzaifa,m,CSE,huzaifa@gmail.com,9876543210,92,Paid,2025-10-03,Delhi,105
41,ST1011,mOhammed,male,Computer Science,mohammed@gmail.com,98765 43210,92,45000,04/12/2025,Delhi,22
42,ST1494,Rahul,female,Artificial Intelligence,rahulgmail.com,+91-9876543210,101%,45000,2025-04-22,Pune,84
43,ST1137,Monica,F,I.T,monica@gamil.com,+91-9876543210,92,45k,03 Apr 26,Delhi,-5
44,ST1207,mOhammed,F,AI&DS,mohammed@gmail.com,09876543210,92,45000,2025-10-26,Pune,105
45,ST1029,Huzaifa,Male,CSE,huzaifa@gamil.com,98765 43210,Absent,45000,17 Oct 25,Bangalore,AB
46,ST1140,Deepak,F,AI&DS,deepak@gmail.com,09876543210,85%,45000,15 Nov 25,Bangalore,AB
47,ST1477,Priya,M,IT,priya@gmail.com,98765 43210,0.78,45k,09 May 25,Hyderabad,AB
48,ST1337,Deepak,female,CSE,deepakgmail.com,09876543210,0.78,45k,23 Feb 25,Chennai,105
49,ST1026,Deepak,m,CSE,balakrishnan@gamil.com,9876543210,85%,45000,2025-07-20,Delhi,-5

In [15]:
stu_details.isna().sum()

Student_ID    0
Name          0
Gender        0
Department    0
Email         0
Phone         0
Attendance    0
Fee           0
Join_Date     0
City          0
Score         0
dtype: int64

## <font color="cyan">Check Duplicate Records</font>
```
df.duplicated()

To count duplicate rows:
df.duplicated().sum()

To remove duplicates:
df.drop_duplicates(inplace=True)

To verify:
print("Duplicates after cleaning:", df.duplicated().sum())

In [28]:
stu_details.duplicated().sum()

np.int64(0)

In [29]:
print("after duplicates are removed \n",stu_details.duplicated())
print("count",stu_details.duplicated().sum())

after duplicates are removed
 0      False
1      False
2      False
3      False
4      False
       ...
596    False
597    False
598    False
599    False
600    False
Length: 601, dtype: bool
count 0

## <font color="cyan">Check Unique Values</font>
```
To count unique values in every column:
df[].nunique() --------->unique value count
df[].uqniue() ----------> SHOWS WHAT ARE THERE

Examples:
df["Category"].nunique()
df["Region"].nunique()
df["Customer Name"].nunique()
df["Product Name"].nunique()

To display the actual unique values:
df["Category"].unique()
df["Region"].unique()
df["Segment"].unique()
```

In [33]:
stu_details["Name"].nunique()

10

In [32]:
stu_details["Name"].unique()

array(['Rahul', 'Aisha', 'John', 'Sara', 'Priya', 'Monica', ' Huzaifa ',
       'Balakrishnan', 'Deepak', 'mOhammed'], dtype=object)

In [34]:
stu_details.nunique()

Student_ID    351
Name           10
Gender          7
Department      8
Email          33
Phone           4
Attendance      5
Fee             5
Join_Date     494
City            5
Score          70
dtype: int64

In [35]:
stu_details.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [49]:
for col in stu_details.columns:
    print("Column Name :",col,"\n",stu_details[col].unique())
    print("Count uniques:",col,":",stu_details[col].nunique(),"\n\n")

Column Name : Student_ID
 ['ST1497' 'ST1350' 'ST1144' 'ST1336' 'ST1509' 'ST1333' 'ST1279' 'ST1146'
 'ST1340' 'ST1108' 'ST1415' 'ST1224' 'ST1072' 'ST1267' 'ST1338' 'ST1240'
 'ST1196' 'ST1453' 'ST1331' 'ST1355' 'ST1179' 'ST1337' 'ST1329' 'ST1203'
 'ST1255' 'ST1303' 'ST1175' 'ST1388' 'ST1138' 'ST1487' 'ST1176' 'ST1248'
 'ST1441' 'ST1187' 'ST1316' 'ST1420' 'ST1404' 'ST1112' 'ST1440' 'ST1449'
 'ST1011' 'ST1494' 'ST1137' 'ST1207' 'ST1029' 'ST1140' 'ST1477' 'ST1026'
 'ST1204' 'ST1166' 'ST1116' 'ST1052' 'ST1084' 'ST1018' 'ST1115' 'ST1244'
 'ST1400' 'ST1096' 'ST1407' 'ST1378' 'ST1300' 'ST1215' 'ST1498' 'ST1503'
 'ST1270' 'ST1027' 'ST1488' 'ST1454' 'ST1042' 'ST1437' 'ST1041' 'ST1123'
 'ST1430' 'ST1434' 'ST1002' 'ST1450' 'ST1185' 'ST1465' 'ST1153' 'ST1010'
 'ST1301' 'ST1212' 'ST1102' 'ST1296' 'ST1307' 'ST1059' 'ST1439' 'ST1177'
 'ST1515' 'ST1448' 'ST1232' 'ST1190' 'ST1308' 'ST1124' 'ST1474' 'ST1249'
 'ST1446' 'ST1214' 'ST1222' 'ST1319' 'ST1128' 'ST1311' 'ST1020' 'ST1330'
 'ST1373' 'ST1427' 'ST1006' 'ST1132' 'ST1262' 'ST1209' 'ST1461' 'ST1093'
 'ST1482' 'ST1495' 'ST1071' 'ST1370' 'ST1383' 'ST1060' 'ST1245' 'ST1223'
 'ST1280' 'ST1205' 'ST1057' 'ST1086' 'ST1043' 'ST1099' 'ST1302' 'ST1180'
 'ST1243' 'ST1291' 'ST1145' 'ST1393' 'ST1289' 'ST1505' 'ST1352' 'ST1133'
 'ST1469' 'ST1000' 'ST1109' 'ST1174' 'ST1120' 'ST1066' 'ST1327' 'ST1069'
 'ST1473' 'ST1380' 'ST1197' 'ST1332' 'ST1208' 'ST1403' 'ST1216' 'ST1475'
 'ST1401' 'ST1459' 'ST1405' 'ST1299' 'ST1127' 'ST1252' 'ST1023' 'ST1233'
 'ST1451' 'ST1513' 'ST1315' 'ST1516' 'ST1063' 'ST1091' 'ST1322' 'ST1192'
 'ST1191' 'ST1502' 'ST1410' 'ST1276' 'ST1464' 'ST1074' 'ST1110' 'ST1129'
 'ST1397' 'ST1025' 'ST1149' 'ST1253' 'ST1088' 'ST1485' 'ST1398' 'ST1188'
 'ST1273' 'ST1365' 'ST1361' 'ST1139' 'ST1092' 'ST1067' 'ST1426' 'ST1283'
 'ST1239' 'ST1266' 'ST1290' 'ST1030' 'ST1211' 'ST1119' 'ST1356' 'ST1455'
 'ST1294' 'ST1268' 'ST1085' 'ST1358' 'ST1390' 'ST1163' 'ST1160' 'ST1281'
 'ST1033' 'ST1195' 'ST1154' 'ST1500' 'ST1409' 'ST1053' 'ST1265' 'ST1424'
 'ST1220' 'ST1387' 'ST1376' 'ST1444' 'ST1050' 'ST1082' 'ST1167' 'ST1504'
 'ST1038' 'ST1261' 'ST1357' 'ST1456' 'ST1359' 'ST1519' 'ST1353' 'ST1114'
 'ST1460' 'ST1323' 'ST1217' 'ST1032' 'ST1408' 'ST1227' 'ST1468' 'ST1312'
 'ST1506' 'ST1221' 'ST1258' 'ST1264' 'ST1385' 'ST1081' 'ST1005' 'ST1257'
 'ST1382' 'ST1037' 'ST1375' 'ST1445' 'ST1394' 'ST1199' 'ST1162' 'ST1098'
 'ST1013' 'ST1478' 'ST1282' 'ST1051' 'ST1157' 'ST1161' 'ST1313' 'ST1075'
 'ST1251' 'ST1235' 'ST1058' 'ST1022' 'ST1305' 'ST1343' 'ST1151' 'ST1395'
 'ST1065' 'ST1158' 'ST1287' 'ST1126' 'ST1104' 'ST1499' 'ST1501' 'ST1447'
 'ST1467' 'ST1418' 'ST1425' 'ST1148' 'ST1078' 'ST1369' 'ST1143' 'ST1003'
 'ST1035' 'ST1412' 'ST1295' 'ST1105' 'ST1269' 'ST1363' 'ST1055' 'ST1508'
 'ST1438' 'ST1297' 'ST1089' 'ST1049' 'ST1001' 'ST1414' 'ST1164' 'ST1076'
 'ST1237' 'ST1419' 'ST1479' 'ST1259' 'ST1077' 'ST1194' 'ST1423' 'ST1171'
 'ST1135' 'ST1318' 'ST1384' 'ST1047' 'ST1136' 'ST1402' 'ST1298' 'ST1416'
 'ST1489' 'ST1335' 'ST1070' 'ST1274' 'ST1142' 'ST1036' 'ST1044' 'ST1480'
 'ST1004' 'ST1491' 'ST1471' 'ST1462' 'ST1511' 'ST1206' 'ST1019' 'ST1309'
 'ST1073' 'ST1325' 'ST1514' 'ST1147' 'ST1107' 'ST1021' 'ST1131' 'ST1068'
 'ST1024' 'ST1170' 'ST1520' 'ST1433' 'ST1247' 'ST1017' 'ST1193']
Count uniques: Student_ID : 351


Column Name : Name
 ['Rahul' 'Aisha' 'John' 'Sara' 'Priya' 'Monica' ' Huzaifa ' 'Balakrishnan'
 'Deepak' 'mOhammed']
Count uniques: Name : 10


Column Name : Gender
 ['female' 'M' 'm' 'Male' 'Female' 'F' 'male']
Count uniques: Gender : 7


Column Name : Department
 ['AI&DS' 'I.T' 'Computer Science' 'IT' 'AI DS' 'CSE'
 'Artificial Intelligence' 'AIDS']
Count uniques: Department : 8


Column Name : Email
 ['balakrishnan@gamil.com' 'saragmail.com' 'priya@gamil.com'
 'monica@gmail.com' 'huzaifa@gmail.com' 'deepak@gamil.com'
 'mohammedgmail.com' 'sara@gamil.com' 'john@gamil.com'
 'mohammed@gamil.com' 'rahulgmail.com' 'balakrishnan@gmail.com'
 'mohammed@gmail.com' 'huzaifa@gamil.com' 'balakrishnangmail.com'
 'rahul@gmail.com' 'user@gamil.com' 'aisha@gamil.com' 'rahul@gamil.com'
 'monica@gamil.com' 'deepak@gmail.com' 'priya@gmail.com' 'deepakgmail.com'
 'user@gmail.com' 'aisha@gmail.com' 'aishagmail.com' 'sara@gmail.com'
 'monicagmail.com' 'john@gmail.com' 'johngmail.com' 'usergmail.com'
 'priyagmail.com' 'huzaifagmail.com']
Count uniques: Email : 33


Column Name : Phone
 ['9876543210' '+91-9876543210' '09876543210' '98765 43210']
Count uniques: Phone : 4


Column Name : Attendance
 ['92' '85%' '0.78' 'Absent' '101%']
Count uniques: Attendance : 5


Column Name : Fee
 ['45k' '?45,000' '?60,500' '45000' 'Paid']
Count uniques: Fee : 5


Column Name : Join_Date
 ['2026-01-31' '10/02/2025' '09/09/2025' '29 Jan 26' '23 Apr 26'
 '17 May 25' '23 Jun 25' '14 Dec 25' '2025-12-30' '29/04/2026' '14 Apr 26'
 '30/04/2026' '2025-12-23' '2026-05-06' '05 Apr 26' '19/05/2025'
 '10 Mar 25' '03 Feb 25' '22/04/2025' '13/10/2025' '2025-10-25'
 '2026-02-01' '04/02/2026' '17 Jul 25' '2025-09-13' '26 Feb 25'
 '26/10/2025' '2025-12-16' '28/02/2025' '10 Feb 25' '30/05/2025'
 '04 May 25' '29/01/2026' '12 Sep 25' '21 Oct 25' '28 Sep 25' '07 Jan 26'
 '2025-03-11' '06/12/2025' '2025-10-03' '04/12/2025' '2025-04-22'
 '03 Apr 26' '2025-10-26' '17 Oct 25' '15 Nov 25' '09 May 25' '23 Feb 25'
 '2025-07-20' '2026-01-07' '10/01/2025' '03 Nov 25' '27/10/2025'
 '08 Feb 25' '23 Jan 25' '31/08/2025' '18/02/2026' '2025-01-30'
 '16/07/2025' '06/07/2025' '2025-04-11' '2025-04-05' '2025-09-03'
 '03/09/2025' '17/02/2026' '2025-03-02' '07 Apr 25' '24/11/2025'
 '25 Apr 26' '15/06/2025' '16/10/2025' '21/02/2025' '2025-10-30'
 '30 Apr 25' '17/02/2025' '11 Feb 26' '27 Sep 25' '18 Aug 25' '10 Dec 25'
 '24 Feb 26' '26/03/2026' '05 Jan 25' '2026-04-09' '25 Feb 26'
 '2025-05-26' '12 Jan 25' '2025-08-03' '2025-09-26' '19/09/2025'
 '16/01/2026' '06/04/2026' '2026-04-27' '25/04/2025' '22/02/2026'
 '2025-07-10' '15/02/2025' '13 Mar 25' '30 Jul 25' '21/02/2026'
 '24/07/2025' '02/02/2026' '2025-12-07' '2025-09-07' '04/05/2026'
 '2025-06-01' '2026-04-15' '2026-01-09' '05/09/2025' '2026-02-15'
 '28/01/2026' '19 Feb 25' '04/02/2025' '08/06/2025' '2025-06-08'
 '06 Sep 25' '24 Mar 26' '2026-01-19' '30 Mar 25' '20/03/2026' '01 Jun 25'
 '13 Sep 25' '05 May 26' '19/02/2025' '2026-03-05' '23 Sep 25'
 '2025-04-30' '28/03/2025' '2025-07-26' '08/09/2025' '31 Jan 26'
 '29 Mar 25' '19/08/2025' '26 Mar 25' '14/08/2025' '24 Jun 25'
 '09/01/2025' '2026-05-07' '24 Jul 25' '2025-03-16' '19 Mar 26'
 '16/06/2025' '2025-03-07' '16 Oct 25' '24/09/2025' '01 Feb 26'
 '28/12/2025' '05 Oct 25' '18 Dec 25' '24/04/2025' '11 Nov 25'
 '2025-01-01' '23/06/2025' '05 Feb 25' '28 Feb 25' '2025-06-14'
 '2025-03-03' '2025-06-21' '27/01/2025' '20/07/2025' '30 Aug 25'
 '23/12/2025' '11 Oct 25' '2025-04-02' '03/06/2025' '22/03/2025'
 '18/08/2025' '14 Aug 25' '25/03/2025' '2025-11-26' '30 May 25'
 '2026-04-25' '23 Jan 26' '06/03/2025' '2026-01-27' '09 Feb 26'
 '2026-01-22' '01 Feb 25' '01 May 25' '2025-09-25' '2025-03-04'
 '2025-08-12' '2026-03-03' '06/06/2025' '19 Mar 25' '2026-03-19'
 '2025-03-20' '22 Apr 25' '13 Jun 25' '17/08/2025' '20 Jul 25' '09 Feb 25'
 '27/06/2025' '17/05/2025' '2025-07-31' '2025-01-15' '12/01/2026'
 '2025-09-21' '11 May 25' '08/12/2025' '07/03/2026' '18 Apr 26'
 '2025-11-25' '2025-11-04' '26 Jan 26' '07 Jan 25' '2025-09-17'
 '2025-07-21' '2025-04-26' '2025-03-18' '2026-03-13' '21/07/2025'
 '18 Jan 26' '2026-03-06' '04 Nov 25' '30 Jan 25' '25/08/2025'
 '09/07/2025' '08/04/2026' '13 Jan 26' '2025-06-19' '02/05/2025'
 '10/07/2025' '2025-04-28' '09 Jul 25' '19 Jan 25' '07/05/2026'
 '17 Jan 25' '27 Aug 25' '01 Aug 25' '27/02/2025' '2026-03-04'
 '2025-06-16' '28/11/2025' '28 Aug 25' '18/03/2026' '03/11/2025'
 '2026-02-05' '16 Jan 25' '21 Jan 25' '09/03/2025' '02/06/2025'
 '09/06/2025' '14/01/2026' '17/04/2025' '2025-04-04' '22 Feb 25'
 '26/05/2025' '2025-05-28' '13 Oct 25' '15/04/2026' '24/02/2026'
 '27/04/2025' '21/08/2025' '28 Jul 25' '20/01/2025' '2026-01-25'
 '2026-01-03' '2025-06-06' '22/12/2025' '26/11/2025' '2026-04-04'
 '2025-02-14' '2026-05-04' '04/05/2025' '2026-04-19' '02 Apr 26'
 '2025-09-08' '2025-10-31' '01/02/2026' '17/01/2025' '23 Aug 25'
 '2025-11-03' '2026-02-08' '06 Dec 25' '22/04/2026' '2025-09-06'
 '31/01/2025' '2025-08-06' '11 Dec 25' '20/05/2025' '07/01/2025'
 '15 Dec 25' '20/11/2025' '2025-08-20' '02/01/2026' '09 Apr 25'
 '10/01/2026' '25 May 25' '2025-07-30' '21/01/2025' '20 Nov 25'
 '14/02/2025' '14/05/2025' '15/05/2025' '02 Oct 25' '2025-03-06'
 '2026-05-10' '2026-04-11' '21 Nov 25' '17 Mar 25' '10 Jul 25'
 '05/01/2026' '14/02/2026' '28 May 25' '31/10/2025' '08/02/2026'
 '2025-08-21' '07/04/2025' '2025-03-14' '05 Jun 25' '06 Mar 26'
 '2025-12-29' '2026-02-21' '23 May 25' '2026-04-16' '2025-01-06'
 '2025-08-30' '25/10/2025' '2025-02-26' '02/04/2025' '20/01/2026'
 '18 Feb 26' '03 Aug 25' '02 Jan 25' '2026-04-22' '2026-05-11'
 '12/11/2025' '16/09/2025' '2025-05-22' '2026-03-10' '01/11/2025'
 '2026-04-28' '01/04/2026' '16 Jan 26' '04 Feb 25' '23/11/2025'
 '2025-11-17' '2025-11-07' '26/03/2025' '27 Oct 25' '2025-07-27'
 '09 Aug 25' '28 Apr 26' '13/08/2025' '19/12/2025' '13/02/2025'
 '22/02/2025' '27/07/2025' '05/02/2025' '21 Jun 25' '2025-08-19'
 '27/04/2026' '2025-08-29' '2026-01-05' '2025-12-17' '2025-11-05'
 '06/03/2026' '2025-10-28' '28 Jan 26' '03 Jun 25' '30/07/2025'
 '17 Apr 25' '13/12/2025' '2025-03-27' '05 Nov 25' '2025-07-29'
 '26/08/2025' '2025-08-08' '07/11/2025' '30 Sep 25' '17/10/2025'
 '2025-01-04' '2026-01-29' '2025-03-05' '07 Jun 25' '2025-01-05'
 '11 Jan 25' '09/02/2026' '04 Aug 25' '09/08/2025' '11 Sep 25' '23 Oct 25'
 '2025-06-04' '20 Apr 26' '09/04/2025' '27/09/2025' '2026-03-09'
 '2025-10-27' '01/06/2025' '2025-06-02' '14 Nov 25' '30/09/2025'
 '06/09/2025' '2025-02-15' '24/08/2025' '2025-06-24' '01 Jul 25'
 '2025-09-27' '19/03/2025' '29/01/2025' '19 Aug 25' '2025-04-16'
 '16/05/2025' '25 Mar 25' '26 Apr 26' '2025-03-26' '2025-12-19'
 '20 May 25' '29/03/2025' '03/10/2025' '09 Dec 25' '08 Nov 25'
 '2025-09-30' '19 May 25' '17 Nov 25' '2025-01-03' '09/10/2025'
 '2026-05-05' '2025-05-20' '25/07/2025' '14 Mar 25' '2025-11-19'
 '2025-12-20' '24 Jan 25' '22/03/2026' '01/10/2025' '2025-07-05'
 '2025-11-30' '05 Jul 25' '16 Feb 26' '05/12/2025' '2026-03-16'
 '17/06/2025' '2025-08-04' '03 Dec 25' '06 Jun 25' '2026-02-11'
 '09 Apr 26' '16/01/2025' '27 Jan 26' '17/12/2025' '04/01/2025'
 '19 Nov 25' '2025-08-24' '01 Jan 26' '2025-10-24' '01/01/2026'
 '2025-04-01' '03/02/2026' '17 Jan 26' '18/09/2025' '11 Apr 25'
 '2025-04-09' '12 Dec 25' '2025-09-19' '2026-05-08' '01 Sep 25'
 '04/04/2026' '2025-01-19' '2025-09-22' '2026-04-23' '2025-07-24'
 '10/02/2026' '05/07/2025' '29 Nov 25' '27/03/2025' '2025-02-04'
 '2025-05-03' '15 May 25' '03/04/2026' '2025-03-13' '2025-02-03'
 '2025-01-10' '2026-02-22' '05 Jan 26' '11/04/2026' '06/01/2025'
 '2025-10-06' '03/03/2026' '18 Feb 25' '31 Oct 25' '13 Apr 26'
 '30/10/2025' '29 Jun 25' '04 Jan 25' '20/10/2025' '2025-08-10'
 '15 Sep 25' '2026-04-05' '27/03/2026' '18 Jan 25' '03/12/2025'
 '25 Apr 25' '14/05/2026']
Count uniques: Join_Date : 494


Column Name : City
 [' Bangalore' 'Delhi' 'Chennai' 'Pune' 'Hyderabad ']
Count uniques: City : 5


Column Name : Score
 ['AB' '69' '105' '100' '83' '-5' '24' '35' '84' '70' '63' '65' '22' '47'
 '40' '99' '64' '89' '98' '44' '49' '30' '62' '90' '31' '55' '26' '27'
 '72' '36' '94' '42' '33' '61' '25' '58' '77' '82' '43' '28' '52' '73'
 '96' '29' '85' '91' '60' '32' '93' '56' '86' '20' '23' '87' '67' '48'
 '57' '97' '50' '76' '38' '75' '95' '34' '59' '51' '21' '78' '71' '53']
Count uniques: Score : 70

In [53]:
for col in stu_details.columns:
    print(f"Column Name :{col} \n {stu_details[col].unique()}")#----->formatted string
    print("Count uniques:",col,":",stu_details[col].nunique(),"\n\n")

Column Name :Student_ID
 ['ST1497' 'ST1350' 'ST1144' 'ST1336' 'ST1509' 'ST1333' 'ST1279' 'ST1146'
 'ST1340' 'ST1108' 'ST1415' 'ST1224' 'ST1072' 'ST1267' 'ST1338' 'ST1240'
 'ST1196' 'ST1453' 'ST1331' 'ST1355' 'ST1179' 'ST1337' 'ST1329' 'ST1203'
 'ST1255' 'ST1303' 'ST1175' 'ST1388' 'ST1138' 'ST1487' 'ST1176' 'ST1248'
 'ST1441' 'ST1187' 'ST1316' 'ST1420' 'ST1404' 'ST1112' 'ST1440' 'ST1449'
 'ST1011' 'ST1494' 'ST1137' 'ST1207' 'ST1029' 'ST1140' 'ST1477' 'ST1026'
 'ST1204' 'ST1166' 'ST1116' 'ST1052' 'ST1084' 'ST1018' 'ST1115' 'ST1244'
 'ST1400' 'ST1096' 'ST1407' 'ST1378' 'ST1300' 'ST1215' 'ST1498' 'ST1503'
 'ST1270' 'ST1027' 'ST1488' 'ST1454' 'ST1042' 'ST1437' 'ST1041' 'ST1123'
 'ST1430' 'ST1434' 'ST1002' 'ST1450' 'ST1185' 'ST1465' 'ST1153' 'ST1010'
 'ST1301' 'ST1212' 'ST1102' 'ST1296' 'ST1307' 'ST1059' 'ST1439' 'ST1177'
 'ST1515' 'ST1448' 'ST1232' 'ST1190' 'ST1308' 'ST1124' 'ST1474' 'ST1249'
 'ST1446' 'ST1214' 'ST1222' 'ST1319' 'ST1128' 'ST1311' 'ST1020' 'ST1330'
 'ST1373' 'ST1427' 'ST1006' 'ST1132' 'ST1262' 'ST1209' 'ST1461' 'ST1093'
 'ST1482' 'ST1495' 'ST1071' 'ST1370' 'ST1383' 'ST1060' 'ST1245' 'ST1223'
 'ST1280' 'ST1205' 'ST1057' 'ST1086' 'ST1043' 'ST1099' 'ST1302' 'ST1180'
 'ST1243' 'ST1291' 'ST1145' 'ST1393' 'ST1289' 'ST1505' 'ST1352' 'ST1133'
 'ST1469' 'ST1000' 'ST1109' 'ST1174' 'ST1120' 'ST1066' 'ST1327' 'ST1069'
 'ST1473' 'ST1380' 'ST1197' 'ST1332' 'ST1208' 'ST1403' 'ST1216' 'ST1475'
 'ST1401' 'ST1459' 'ST1405' 'ST1299' 'ST1127' 'ST1252' 'ST1023' 'ST1233'
 'ST1451' 'ST1513' 'ST1315' 'ST1516' 'ST1063' 'ST1091' 'ST1322' 'ST1192'
 'ST1191' 'ST1502' 'ST1410' 'ST1276' 'ST1464' 'ST1074' 'ST1110' 'ST1129'
 'ST1397' 'ST1025' 'ST1149' 'ST1253' 'ST1088' 'ST1485' 'ST1398' 'ST1188'
 'ST1273' 'ST1365' 'ST1361' 'ST1139' 'ST1092' 'ST1067' 'ST1426' 'ST1283'
 'ST1239' 'ST1266' 'ST1290' 'ST1030' 'ST1211' 'ST1119' 'ST1356' 'ST1455'
 'ST1294' 'ST1268' 'ST1085' 'ST1358' 'ST1390' 'ST1163' 'ST1160' 'ST1281'
 'ST1033' 'ST1195' 'ST1154' 'ST1500' 'ST1409' 'ST1053' 'ST1265' 'ST1424'
 'ST1220' 'ST1387' 'ST1376' 'ST1444' 'ST1050' 'ST1082' 'ST1167' 'ST1504'
 'ST1038' 'ST1261' 'ST1357' 'ST1456' 'ST1359' 'ST1519' 'ST1353' 'ST1114'
 'ST1460' 'ST1323' 'ST1217' 'ST1032' 'ST1408' 'ST1227' 'ST1468' 'ST1312'
 'ST1506' 'ST1221' 'ST1258' 'ST1264' 'ST1385' 'ST1081' 'ST1005' 'ST1257'
 'ST1382' 'ST1037' 'ST1375' 'ST1445' 'ST1394' 'ST1199' 'ST1162' 'ST1098'
 'ST1013' 'ST1478' 'ST1282' 'ST1051' 'ST1157' 'ST1161' 'ST1313' 'ST1075'
 'ST1251' 'ST1235' 'ST1058' 'ST1022' 'ST1305' 'ST1343' 'ST1151' 'ST1395'
 'ST1065' 'ST1158' 'ST1287' 'ST1126' 'ST1104' 'ST1499' 'ST1501' 'ST1447'
 'ST1467' 'ST1418' 'ST1425' 'ST1148' 'ST1078' 'ST1369' 'ST1143' 'ST1003'
 'ST1035' 'ST1412' 'ST1295' 'ST1105' 'ST1269' 'ST1363' 'ST1055' 'ST1508'
 'ST1438' 'ST1297' 'ST1089' 'ST1049' 'ST1001' 'ST1414' 'ST1164' 'ST1076'
 'ST1237' 'ST1419' 'ST1479' 'ST1259' 'ST1077' 'ST1194' 'ST1423' 'ST1171'
 'ST1135' 'ST1318' 'ST1384' 'ST1047' 'ST1136' 'ST1402' 'ST1298' 'ST1416'
 'ST1489' 'ST1335' 'ST1070' 'ST1274' 'ST1142' 'ST1036' 'ST1044' 'ST1480'
 'ST1004' 'ST1491' 'ST1471' 'ST1462' 'ST1511' 'ST1206' 'ST1019' 'ST1309'
 'ST1073' 'ST1325' 'ST1514' 'ST1147' 'ST1107' 'ST1021' 'ST1131' 'ST1068'
 'ST1024' 'ST1170' 'ST1520' 'ST1433' 'ST1247' 'ST1017' 'ST1193']
Count uniques: Student_ID : 351


Column Name :Name
 ['Rahul' 'Aisha' 'John' 'Sara' 'Priya' 'Monica' ' Huzaifa ' 'Balakrishnan'
 'Deepak' 'mOhammed']
Count uniques: Name : 10


Column Name :Gender
 ['female' 'M' 'm' 'Male' 'Female' 'F' 'male']
Count uniques: Gender : 7


Column Name :Department
 ['AI&DS' 'I.T' 'Computer Science' 'IT' 'AI DS' 'CSE'
 'Artificial Intelligence' 'AIDS']
Count uniques: Department : 8


Column Name :Email
 ['balakrishnan@gamil.com' 'saragmail.com' 'priya@gamil.com'
 'monica@gmail.com' 'huzaifa@gmail.com' 'deepak@gamil.com'
 'mohammedgmail.com' 'sara@gamil.com' 'john@gamil.com'
 'mohammed@gamil.com' 'rahulgmail.com' 'balakrishnan@gmail.com'
 'mohammed@gmail.com' 'huzaifa@gamil.com' 'balakrishnangmail.com'
 'rahul@gmail.com' 'user@gamil.com' 'aisha@gamil.com' 'rahul@gamil.com'
 'monica@gamil.com' 'deepak@gmail.com' 'priya@gmail.com' 'deepakgmail.com'
 'user@gmail.com' 'aisha@gmail.com' 'aishagmail.com' 'sara@gmail.com'
 'monicagmail.com' 'john@gmail.com' 'johngmail.com' 'usergmail.com'
 'priyagmail.com' 'huzaifagmail.com']
Count uniques: Email : 33


Column Name :Phone
 ['9876543210' '+91-9876543210' '09876543210' '98765 43210']
Count uniques: Phone : 4


Column Name :Attendance
 ['92' '85%' '0.78' 'Absent' '101%']
Count uniques: Attendance : 5


Column Name :Fee
 ['45k' '?45,000' '?60,500' '45000' 'Paid']
Count uniques: Fee : 5


Column Name :Join_Date
 ['2026-01-31' '10/02/2025' '09/09/2025' '29 Jan 26' '23 Apr 26'
 '17 May 25' '23 Jun 25' '14 Dec 25' '2025-12-30' '29/04/2026' '14 Apr 26'
 '30/04/2026' '2025-12-23' '2026-05-06' '05 Apr 26' '19/05/2025'
 '10 Mar 25' '03 Feb 25' '22/04/2025' '13/10/2025' '2025-10-25'
 '2026-02-01' '04/02/2026' '17 Jul 25' '2025-09-13' '26 Feb 25'
 '26/10/2025' '2025-12-16' '28/02/2025' '10 Feb 25' '30/05/2025'
 '04 May 25' '29/01/2026' '12 Sep 25' '21 Oct 25' '28 Sep 25' '07 Jan 26'
 '2025-03-11' '06/12/2025' '2025-10-03' '04/12/2025' '2025-04-22'
 '03 Apr 26' '2025-10-26' '17 Oct 25' '15 Nov 25' '09 May 25' '23 Feb 25'
 '2025-07-20' '2026-01-07' '10/01/2025' '03 Nov 25' '27/10/2025'
 '08 Feb 25' '23 Jan 25' '31/08/2025' '18/02/2026' '2025-01-30'
 '16/07/2025' '06/07/2025' '2025-04-11' '2025-04-05' '2025-09-03'
 '03/09/2025' '17/02/2026' '2025-03-02' '07 Apr 25' '24/11/2025'
 '25 Apr 26' '15/06/2025' '16/10/2025' '21/02/2025' '2025-10-30'
 '30 Apr 25' '17/02/2025' '11 Feb 26' '27 Sep 25' '18 Aug 25' '10 Dec 25'
 '24 Feb 26' '26/03/2026' '05 Jan 25' '2026-04-09' '25 Feb 26'
 '2025-05-26' '12 Jan 25' '2025-08-03' '2025-09-26' '19/09/2025'
 '16/01/2026' '06/04/2026' '2026-04-27' '25/04/2025' '22/02/2026'
 '2025-07-10' '15/02/2025' '13 Mar 25' '30 Jul 25' '21/02/2026'
 '24/07/2025' '02/02/2026' '2025-12-07' '2025-09-07' '04/05/2026'
 '2025-06-01' '2026-04-15' '2026-01-09' '05/09/2025' '2026-02-15'
 '28/01/2026' '19 Feb 25' '04/02/2025' '08/06/2025' '2025-06-08'
 '06 Sep 25' '24 Mar 26' '2026-01-19' '30 Mar 25' '20/03/2026' '01 Jun 25'
 '13 Sep 25' '05 May 26' '19/02/2025' '2026-03-05' '23 Sep 25'
 '2025-04-30' '28/03/2025' '2025-07-26' '08/09/2025' '31 Jan 26'
 '29 Mar 25' '19/08/2025' '26 Mar 25' '14/08/2025' '24 Jun 25'
 '09/01/2025' '2026-05-07' '24 Jul 25' '2025-03-16' '19 Mar 26'
 '16/06/2025' '2025-03-07' '16 Oct 25' '24/09/2025' '01 Feb 26'
 '28/12/2025' '05 Oct 25' '18 Dec 25' '24/04/2025' '11 Nov 25'
 '2025-01-01' '23/06/2025' '05 Feb 25' '28 Feb 25' '2025-06-14'
 '2025-03-03' '2025-06-21' '27/01/2025' '20/07/2025' '30 Aug 25'
 '23/12/2025' '11 Oct 25' '2025-04-02' '03/06/2025' '22/03/2025'
 '18/08/2025' '14 Aug 25' '25/03/2025' '2025-11-26' '30 May 25'
 '2026-04-25' '23 Jan 26' '06/03/2025' '2026-01-27' '09 Feb 26'
 '2026-01-22' '01 Feb 25' '01 May 25' '2025-09-25' '2025-03-04'
 '2025-08-12' '2026-03-03' '06/06/2025' '19 Mar 25' '2026-03-19'
 '2025-03-20' '22 Apr 25' '13 Jun 25' '17/08/2025' '20 Jul 25' '09 Feb 25'
 '27/06/2025' '17/05/2025' '2025-07-31' '2025-01-15' '12/01/2026'
 '2025-09-21' '11 May 25' '08/12/2025' '07/03/2026' '18 Apr 26'
 '2025-11-25' '2025-11-04' '26 Jan 26' '07 Jan 25' '2025-09-17'
 '2025-07-21' '2025-04-26' '2025-03-18' '2026-03-13' '21/07/2025'
 '18 Jan 26' '2026-03-06' '04 Nov 25' '30 Jan 25' '25/08/2025'
 '09/07/2025' '08/04/2026' '13 Jan 26' '2025-06-19' '02/05/2025'
 '10/07/2025' '2025-04-28' '09 Jul 25' '19 Jan 25' '07/05/2026'
 '17 Jan 25' '27 Aug 25' '01 Aug 25' '27/02/2025' '2026-03-04'
 '2025-06-16' '28/11/2025' '28 Aug 25' '18/03/2026' '03/11/2025'
 '2026-02-05' '16 Jan 25' '21 Jan 25' '09/03/2025' '02/06/2025'
 '09/06/2025' '14/01/2026' '17/04/2025' '2025-04-04' '22 Feb 25'
 '26/05/2025' '2025-05-28' '13 Oct 25' '15/04/2026' '24/02/2026'
 '27/04/2025' '21/08/2025' '28 Jul 25' '20/01/2025' '2026-01-25'
 '2026-01-03' '2025-06-06' '22/12/2025' '26/11/2025' '2026-04-04'
 '2025-02-14' '2026-05-04' '04/05/2025' '2026-04-19' '02 Apr 26'
 '2025-09-08' '2025-10-31' '01/02/2026' '17/01/2025' '23 Aug 25'
 '2025-11-03' '2026-02-08' '06 Dec 25' '22/04/2026' '2025-09-06'
 '31/01/2025' '2025-08-06' '11 Dec 25' '20/05/2025' '07/01/2025'
 '15 Dec 25' '20/11/2025' '2025-08-20' '02/01/2026' '09 Apr 25'
 '10/01/2026' '25 May 25' '2025-07-30' '21/01/2025' '20 Nov 25'
 '14/02/2025' '14/05/2025' '15/05/2025' '02 Oct 25' '2025-03-06'
 '2026-05-10' '2026-04-11' '21 Nov 25' '17 Mar 25' '10 Jul 25'
 '05/01/2026' '14/02/2026' '28 May 25' '31/10/2025' '08/02/2026'
 '2025-08-21' '07/04/2025' '2025-03-14' '05 Jun 25' '06 Mar 26'
 '2025-12-29' '2026-02-21' '23 May 25' '2026-04-16' '2025-01-06'
 '2025-08-30' '25/10/2025' '2025-02-26' '02/04/2025' '20/01/2026'
 '18 Feb 26' '03 Aug 25' '02 Jan 25' '2026-04-22' '2026-05-11'
 '12/11/2025' '16/09/2025' '2025-05-22' '2026-03-10' '01/11/2025'
 '2026-04-28' '01/04/2026' '16 Jan 26' '04 Feb 25' '23/11/2025'
 '2025-11-17' '2025-11-07' '26/03/2025' '27 Oct 25' '2025-07-27'
 '09 Aug 25' '28 Apr 26' '13/08/2025' '19/12/2025' '13/02/2025'
 '22/02/2025' '27/07/2025' '05/02/2025' '21 Jun 25' '2025-08-19'
 '27/04/2026' '2025-08-29' '2026-01-05' '2025-12-17' '2025-11-05'
 '06/03/2026' '2025-10-28' '28 Jan 26' '03 Jun 25' '30/07/2025'
 '17 Apr 25' '13/12/2025' '2025-03-27' '05 Nov 25' '2025-07-29'
 '26/08/2025' '2025-08-08' '07/11/2025' '30 Sep 25' '17/10/2025'
 '2025-01-04' '2026-01-29' '2025-03-05' '07 Jun 25' '2025-01-05'
 '11 Jan 25' '09/02/2026' '04 Aug 25' '09/08/2025' '11 Sep 25' '23 Oct 25'
 '2025-06-04' '20 Apr 26' '09/04/2025' '27/09/2025' '2026-03-09'
 '2025-10-27' '01/06/2025' '2025-06-02' '14 Nov 25' '30/09/2025'
 '06/09/2025' '2025-02-15' '24/08/2025' '2025-06-24' '01 Jul 25'
 '2025-09-27' '19/03/2025' '29/01/2025' '19 Aug 25' '2025-04-16'
 '16/05/2025' '25 Mar 25' '26 Apr 26' '2025-03-26' '2025-12-19'
 '20 May 25' '29/03/2025' '03/10/2025' '09 Dec 25' '08 Nov 25'
 '2025-09-30' '19 May 25' '17 Nov 25' '2025-01-03' '09/10/2025'
 '2026-05-05' '2025-05-20' '25/07/2025' '14 Mar 25' '2025-11-19'
 '2025-12-20' '24 Jan 25' '22/03/2026' '01/10/2025' '2025-07-05'
 '2025-11-30' '05 Jul 25' '16 Feb 26' '05/12/2025' '2026-03-16'
 '17/06/2025' '2025-08-04' '03 Dec 25' '06 Jun 25' '2026-02-11'
 '09 Apr 26' '16/01/2025' '27 Jan 26' '17/12/2025' '04/01/2025'
 '19 Nov 25' '2025-08-24' '01 Jan 26' '2025-10-24' '01/01/2026'
 '2025-04-01' '03/02/2026' '17 Jan 26' '18/09/2025' '11 Apr 25'
 '2025-04-09' '12 Dec 25' '2025-09-19' '2026-05-08' '01 Sep 25'
 '04/04/2026' '2025-01-19' '2025-09-22' '2026-04-23' '2025-07-24'
 '10/02/2026' '05/07/2025' '29 Nov 25' '27/03/2025' '2025-02-04'
 '2025-05-03' '15 May 25' '03/04/2026' '2025-03-13' '2025-02-03'
 '2025-01-10' '2026-02-22' '05 Jan 26' '11/04/2026' '06/01/2025'
 '2025-10-06' '03/03/2026' '18 Feb 25' '31 Oct 25' '13 Apr 26'
 '30/10/2025' '29 Jun 25' '04 Jan 25' '20/10/2025' '2025-08-10'
 '15 Sep 25' '2026-04-05' '27/03/2026' '18 Jan 25' '03/12/2025'
 '25 Apr 25' '14/05/2026']
Count uniques: Join_Date : 494


Column Name :City
 [' Bangalore' 'Delhi' 'Chennai' 'Pune' 'Hyderabad ']
Count uniques: City : 5


Column Name :Score
 ['AB' '69' '105' '100' '83' '-5' '24' '35' '84' '70' '63' '65' '22' '47'
 '40' '99' '64' '89' '98' '44' '49' '30' '62' '90' '31' '55' '26' '27'
 '72' '36' '94' '42' '33' '61' '25' '58' '77' '82' '43' '28' '52' '73'
 '96' '29' '85' '91' '60' '32' '93' '56' '86' '20' '23' '87' '67' '48'
 '57' '97' '50' '76' '38' '75' '95' '34' '59' '51' '21' '78' '71' '53']
Count uniques: Score : 70

## <font color="cyan">Frequency Distribution Using value_counts() </font>
```
value_counts() shows how many times each category appears.

df["Category"].value_counts()
df["Region"].value_counts()
df["Segment"].value_counts()

To display percentages:
df["Category"].value_counts(normalize=True) * 100
```

In [58]:
print(stu_details["Name"].value_counts())
print(stu_details["Name"].nunique())
print(stu_details["Name"].unique())

Name
Deepak          97
Rahul           64
Monica          62
John            62
Balakrishnan    60
Sara            58
Aisha           55
Priya           48
mOhammed        48
 Huzaifa        47
Name: count, dtype: int64
10
['Rahul' 'Aisha' 'John' 'Sara' 'Priya' 'Monica' ' Huzaifa ' 'Balakrishnan'
 'Deepak' 'mOhammed']

<h2 style="color:#FFEA00;">
    The above functions are widely using repeatively <br>
    remainders are lets see along with the program or real code
</h2>
<h1>🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥🐦‍🔥</h1>
<h1>BE CONFIDENT😎,BE CONSISTENT⏩, BE FORYOURSELF🔎,BE HAPPY😊</h1>